export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstant = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
}

export const categoryConstant = {
    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
}

export const serviceConstant = {
    GET_SERVICE_REQUEST: 'GET_SERVICE_REQUEST',
    GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
    GET_SERVICE_FAILURE: 'GET_SERVICE_FAILURE',
}

export const startingDataConstant = {
    GET_STARTING_DATA_REQUEST: 'GET_STARTING_DATA_REQUEST:',
    GET_STARTING_DATA_SUCCESS: 'GET_STARTING_DATA_SUCCESS:',
    GET_STARTING_DATA_FAILURE: 'GET_STARTING_DATA_FAILURE:',
}